import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import { Upload, Images } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased flex flex-col min-w-screen`}
        >
          {/* Navbar Section */}
          <div className="h-20 bg-white border-b-2 fixed top-0 left-0 right-0 z-50">
            <div className="relative top-5 flex flex-row text-sm md:text-lg justify-center gap-x-28 items-center font-poppins">
              {/* Upload & Edit */}
              <div className="w-32 text-center">
                <Link href="/uploads">
                  <div className="relative">
                    <p>Upload & Edit</p>
                    <div className="opacity-15 absolute -right-3 -top-5">
                      <Upload className="w-14 h-14" />
                    </div>
                  </div>
                </Link>
              </div>

              {/* Gallery */}
              <div className="w-32 text-center">
                <Link href="/gallery">
                  <div className="relative">
                    <p>Gallery</p>
                    <div className="opacity-15 absolute -right-0 -top-5">
                      <Images className="w-14 h-14" />
                    </div>
                  </div>
                </Link>
              </div>

              {/* Account */}
              <div className="w-32 text-center">
                <div className="relative">
                  <SignedOut>
                    <div className="flex flex-col gap-1 items-center">
                      <SignInButton />
                      <SignUpButton />
                    </div>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                  <div className="opacity-15 absolute -right-3 -top-3">
                    <Upload className="w-14 h-14" />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Main Content Area */}
          <div className="flex-1 pt-20">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
