import {
  ClerkLoaded,
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Images, LogIn, MenuIcon, Upload } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/700.css";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased flex flex-col min-w-screen">
          {/* Navbar */}
          <div className="h-20 bg-white border-b-2 fixed top-0 left-0 right-0 z-50 shadow-md flex items-center justify-between px-4 sm:px-8 md:px-20">
            <ClerkLoaded>
              {/* Left - Logo */}
              <div className="flex items-center">
                <Link href="/uploads">
                  <Image src="/logo2.png" alt="logo" width={100} height={100} />
                </Link>
              </div>

              {/* Center - Nav Links */}
              <div className="hidden sm:flex absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 flex-row justify-center items-center gap-x-6 md:gap-x-12 font-poppins text-sm md:text-lg">
                <Link href="/uploads">
                  <div className="relative text-center">
                    <p>Upload & Edit</p>
                    <Upload className="w-6 h-6 opacity-10 absolute -right-5 -top-3" />
                  </div>
                </Link>
                <Link href="/gallery">
                  <div className="relative text-center">
                    <p>Gallery</p>
                    <Images className="w-6 h-6 opacity-10 absolute -right-4 -top-3" />
                  </div>
                </Link>
              </div>

              {/* Mobile Nav (visible only on mobile) */}
              <div className="flex sm:hidden">
                <DropdownMenu>
                  <DropdownMenuTrigger className="p-2">
                    <MenuIcon className="w-6 h-6" />
                  </DropdownMenuTrigger>
                  <DropdownMenuContent className="w-40">
                    <DropdownMenuItem asChild>
                      <Link href="/uploads">Upload & Edit</Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <Link href="/gallery">Gallery</Link>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>

              {/* Right - Auth */}
              <div className="flex items-center">
                <SignedOut>
                  <div className="flex items-center gap-2 sm:gap-3">
                    <SignInButton />
                    <span className="text-gray-400 hidden sm:inline">|</span>
                    <SignUpButton />
                    <LogIn className="w-6 h-6 opacity-10 hidden sm:block" />
                  </div>
                </SignedOut>
                <SignedIn>
                  <UserButton
                    appearance={{
                      elements: {
                        userButtonAvatarBox: {
                          width: "35px",
                          height: "35px",
                        },
                      },
                    }}
                  />
                </SignedIn>
              </div>
            </ClerkLoaded>
          </div>

          {/* Main Content */}
          <div className="flex-1 pt-20 bg-[url('/background.svg')] bg-no-repeat bg-cover bg-center min-h-screen">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
